wandb_version: 1

exp_name:
  desc: null
  value: ppo
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: cleanRL
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: true
env_id:
  desc: null
  value: CartPole-v1
total_timesteps:
  desc: null
  value: 50000
learning_rate:
  desc: null
  value: 0.00025
num_envs:
  desc: null
  value: 4
num_steps:
  desc: null
  value: 128
anneal_lr:
  desc: null
  value: true
gae:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 4
update_epochs:
  desc: null
  value: 4
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
target_kl:
  desc: null
  value: null
repo_id:
  desc: null
  value: georgysavva/ppo-CartPole-v1
batch_size:
  desc: null
  value: 512
minibatch_size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    code_path: code/Unit8-PPO/ppo.py
    python_version: 3.10.14
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719339499
    t:
      1:
      - 1
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.14
      5: 0.17.2
      8:
      - 5
      13: linux-x86_64
